version: '3.7'
services:
  postgres:
    container_name: postgres
    networks:
      - ubemed
    image: postgres:13.2-alpine
    restart: always
    # use expose when "production mode"
#    expose:
#      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ubemed
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    networks:
      - ubemed
    image: chorss/docker-pgadmin4
    container_name: pgadmin4
    depends_on:
      - postgres
    # remove ports when in prod mode
    ports:
      - "5050:5050"
  java:
    networks:
      - ubemed
    image: openjdk:11-jdk
    container_name: java
    expose:
      - 8080
    restart: always
    build:
      context: app
      dockerfile: "Dockerfile"
    environment:
      - server_ip=http://37.157.81.108:8081
      - jwt.secret=test
      - postgres_username=sa
      - postgres_password=sa
      - postgres_url=jdbc:postgresql://postgres:5432/postgres
  nginx:
    networks:
      - ubemed
    container_name: nginx
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "8081:80"

networks:
  ubemed:

volumes:
  postgres:
