version: '3.7'
services:
  postgres:
    container_name: postgres
    networks:
      - ubemed
    image: postgres:13.2-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ubemed
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    networks:
      - ubemed
    image: chorss/docker-pgadmin4
    container_name: pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:5050"

networks:
  ubemed:

volumes:
  postgres:
